### ISSUE TITLE
Create Initial Landing Page

### ISSUE THREAD

**Issue by darnjo** [RESOStandards/reso-certification-help#1]
The goal of this issue is to create a README.md page at the top level of the project that links to the related sub pages, such as `/docs/guides/admin.md`.

Tasks:
- [x] Create README and Table of Contents. This is also the stub for consumer content.
- [x] Create admin.md page stub.
- [x] Create provider.md page stub.
- [x] Create recipient.md page stub.
- [x] Work on template look and feel. For example, remove unnecessary links from the template.

**Comment by darnjo** [comment]
Some of this structure has been created in the main branch. What's left is to come up with a final table of contents and to create a consistent style for each sub page, for example the heading and a brief overview or summary of the section. This could be a table of contents for the section as well.

**Comment by Jad212s** [comment]
Here is the Provider guide as a Google doc - [https://docs.google.com/document/d/16h311fH-6tzZp_ok9qBOycpPGAFjj_jKj6eqF-EGpPM/edit?usp=sharing](url)

**Comment by darnjo** [comment]
Some work has been done and there's a PR for the Provider and Recipient content. See #2
